// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Create_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *Create_ID) Reset() {
	*x = Create_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_ID) ProtoMessage() {}

func (x *Create_ID) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_ID.ProtoReflect.Descriptor instead.
func (*Create_ID) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *Create_ID) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type Token_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cinfo string `protobuf:"bytes,1,opt,name=cinfo,proto3" json:"cinfo,omitempty"`
}

func (x *Token_Info) Reset() {
	*x = Token_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token_Info) ProtoMessage() {}

func (x *Token_Info) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token_Info.ProtoReflect.Descriptor instead.
func (*Token_Info) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{1}
}

func (x *Token_Info) GetCinfo() string {
	if x != nil {
		return x.Cinfo
	}
	return ""
}

type Read_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Readid string `protobuf:"bytes,1,opt,name=readid,proto3" json:"readid,omitempty"`
}

func (x *Read_ID) Reset() {
	*x = Read_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read_ID) ProtoMessage() {}

func (x *Read_ID) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read_ID.ProtoReflect.Descriptor instead.
func (*Read_ID) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{2}
}

func (x *Read_ID) GetReadid() string {
	if x != nil {
		return x.Readid
	}
	return ""
}

type Final struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid   string `protobuf:"bytes,4,opt,name=rid,proto3" json:"rid,omitempty"`
	Rname string `protobuf:"bytes,5,opt,name=rname,proto3" json:"rname,omitempty"`
	Low   uint64 `protobuf:"varint,6,opt,name=low,proto3" json:"low,omitempty"`
	Rhigh uint64 `protobuf:"varint,7,opt,name=rhigh,proto3" json:"rhigh,omitempty"`
	Rmid  uint64 `protobuf:"varint,8,opt,name=rmid,proto3" json:"rmid,omitempty"`
	Rts   int64  `protobuf:"varint,9,opt,name=rts,proto3" json:"rts,omitempty"`
	Final uint64 `protobuf:"varint,1,opt,name=final,proto3" json:"final,omitempty"`
	Info  string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Ts    int64  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Final) Reset() {
	*x = Final{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Final) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Final) ProtoMessage() {}

func (x *Final) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Final.ProtoReflect.Descriptor instead.
func (*Final) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{3}
}

func (x *Final) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Final) GetRname() string {
	if x != nil {
		return x.Rname
	}
	return ""
}

func (x *Final) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Final) GetRhigh() uint64 {
	if x != nil {
		return x.Rhigh
	}
	return 0
}

func (x *Final) GetRmid() uint64 {
	if x != nil {
		return x.Rmid
	}
	return 0
}

func (x *Final) GetRts() int64 {
	if x != nil {
		return x.Rts
	}
	return 0
}

func (x *Final) GetFinal() uint64 {
	if x != nil {
		return x.Final
	}
	return 0
}

func (x *Final) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Final) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Write_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wlow  uint64 `protobuf:"varint,3,opt,name=wlow,proto3" json:"wlow,omitempty"`
	Whigh uint64 `protobuf:"varint,4,opt,name=whigh,proto3" json:"whigh,omitempty"`
	Wmid  uint64 `protobuf:"varint,5,opt,name=wmid,proto3" json:"wmid,omitempty"`
	Wid   string `protobuf:"bytes,1,opt,name=wid,proto3" json:"wid,omitempty"`
	Wname string `protobuf:"bytes,2,opt,name=wname,proto3" json:"wname,omitempty"`
	Wts   int64  `protobuf:"varint,6,opt,name=wts,proto3" json:"wts,omitempty"`
}

func (x *Write_ID) Reset() {
	*x = Write_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Write_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_ID) ProtoMessage() {}

func (x *Write_ID) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_ID.ProtoReflect.Descriptor instead.
func (*Write_ID) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{4}
}

func (x *Write_ID) GetWlow() uint64 {
	if x != nil {
		return x.Wlow
	}
	return 0
}

func (x *Write_ID) GetWhigh() uint64 {
	if x != nil {
		return x.Whigh
	}
	return 0
}

func (x *Write_ID) GetWmid() uint64 {
	if x != nil {
		return x.Wmid
	}
	return 0
}

func (x *Write_ID) GetWid() string {
	if x != nil {
		return x.Wid
	}
	return ""
}

func (x *Write_ID) GetWname() string {
	if x != nil {
		return x.Wname
	}
	return ""
}

func (x *Write_ID) GetWts() int64 {
	if x != nil {
		return x.Wts
	}
	return 0
}

type Partial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pinfo  string `protobuf:"bytes,2,opt,name=pinfo,proto3" json:"pinfo,omitempty"`
	Pvalue uint64 `protobuf:"varint,1,opt,name=pvalue,proto3" json:"pvalue,omitempty"`
}

func (x *Partial) Reset() {
	*x = Partial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partial) ProtoMessage() {}

func (x *Partial) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partial.ProtoReflect.Descriptor instead.
func (*Partial) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{5}
}

func (x *Partial) GetPinfo() string {
	if x != nil {
		return x.Pinfo
	}
	return ""
}

func (x *Partial) GetPvalue() uint64 {
	if x != nil {
		return x.Pvalue
	}
	return 0
}

type Drop_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Drop_Info) Reset() {
	*x = Drop_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drop_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drop_Info) ProtoMessage() {}

func (x *Drop_Info) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drop_Info.ProtoReflect.Descriptor instead.
func (*Drop_Info) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{6}
}

type Drop_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *Drop_ID) Reset() {
	*x = Drop_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drop_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drop_ID) ProtoMessage() {}

func (x *Drop_ID) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drop_ID.ProtoReflect.Descriptor instead.
func (*Drop_ID) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{7}
}

func (x *Drop_ID) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

var File_token_token_proto protoreflect.FileDescriptor

var file_token_token_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1d, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x21, 0x0a,
	0x07, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x69, 0x64,
	0x22, 0xb7, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x68, 0x69, 0x67, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x68, 0x69, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6d,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x72, 0x6d, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x5f, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6c, 0x6f, 0x77, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x77, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x68, 0x69, 0x67, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x77, 0x68, 0x69, 0x67,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6d, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x77, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x77, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x77, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x77, 0x74, 0x73, 0x22,
	0x37, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x70, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70,
	0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1b, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x69, 0x64, 0x32, 0xd8, 0x01, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0b, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x49, 0x44, 0x1a, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x44, 0x72, 0x6f, 0x70, 0x12, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x49, 0x44, 0x1a, 0x10, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x13, 0x5a,
	0x11, 0x50, 0x72, 0x6f, 0x6a, 0x33, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3b, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_token_proto_rawDescOnce sync.Once
	file_token_token_proto_rawDescData = file_token_token_proto_rawDesc
)

func file_token_token_proto_rawDescGZIP() []byte {
	file_token_token_proto_rawDescOnce.Do(func() {
		file_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_token_proto_rawDescData)
	})
	return file_token_token_proto_rawDescData
}

var file_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_token_token_proto_goTypes = []interface{}{
	(*Create_ID)(nil),  // 0: token.Create_ID
	(*Token_Info)(nil), // 1: token.Token_Info
	(*Read_ID)(nil),    // 2: token.Read_ID
	(*Final)(nil),      // 3: token.Final
	(*Write_ID)(nil),   // 4: token.Write_ID
	(*Partial)(nil),    // 5: token.Partial
	(*Drop_Info)(nil),  // 6: token.Drop_Info
	(*Drop_ID)(nil),    // 7: token.Drop_ID
}
var file_token_token_proto_depIdxs = []int32{
	0, // 0: token.token_service.Token_Create:input_type -> token.Create_ID
	2, // 1: token.token_service.Token_Read:input_type -> token.Read_ID
	4, // 2: token.token_service.Token_Write:input_type -> token.Write_ID
	7, // 3: token.token_service.Token_Drop:input_type -> token.Drop_ID
	1, // 4: token.token_service.Token_Create:output_type -> token.Token_Info
	3, // 5: token.token_service.Token_Read:output_type -> token.Final
	5, // 6: token.token_service.Token_Write:output_type -> token.Partial
	6, // 7: token.token_service.Token_Drop:output_type -> token.Drop_Info
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_token_proto_init() }
func file_token_token_proto_init() {
	if File_token_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Final); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Write_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drop_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drop_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_token_proto_goTypes,
		DependencyIndexes: file_token_token_proto_depIdxs,
		MessageInfos:      file_token_token_proto_msgTypes,
	}.Build()
	File_token_token_proto = out.File
	file_token_token_proto_rawDesc = nil
	file_token_token_proto_goTypes = nil
	file_token_token_proto_depIdxs = nil
}
